# Project: Project1
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Proyeksi.o KubusBerotasi.o Lenganbergerak.o
LINKOBJ  = Proyeksi.o KubusBerotasi.o Lenganbergerak.o
LIBS     = -L"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib" -L"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Proyeksi.o: Proyeksi.cpp
	$(CPP) -c Proyeksi.cpp -o Proyeksi.o $(CXXFLAGS)

KubusBerotasi.o: KubusBerotasi.cpp
	$(CPP) -c KubusBerotasi.cpp -o KubusBerotasi.o $(CXXFLAGS)

Lenganbergerak.o: Lenganbergerak.cpp
	$(CPP) -c Lenganbergerak.cpp -o Lenganbergerak.o $(CXXFLAGS)
