# Project: pertemuan2
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = translasi.o rotasi.o transformasi.o snowflake.o
LINKOBJ  = translasi.o rotasi.o transformasi.o snowflake.o
LIBS     = -L"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib" -L"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Users/asust/Downloads/Dev-Cpp/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = pertemuan2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

translasi.o: translasi.cpp
	$(CPP) -c translasi.cpp -o translasi.o $(CXXFLAGS)

rotasi.o: rotasi.cpp
	$(CPP) -c rotasi.cpp -o rotasi.o $(CXXFLAGS)

transformasi.o: transformasi.cpp
	$(CPP) -c transformasi.cpp -o transformasi.o $(CXXFLAGS)

snowflake.o: snowflake.cpp
	$(CPP) -c snowflake.cpp -o snowflake.o $(CXXFLAGS)
